import { Data as EJSData } from 'ejs';
import { PassportStatic, Strategy as PassportStrategy } from 'passport';
import { Superlogin } from './types';
export declare type DBType = Superlogin.DBType;
export declare type Data = EJSData;
export declare type IActivity = Superlogin.IActivity;
export declare type IAdapter = Superlogin.IAdapter;
export declare type IBaseSLInstance = Superlogin.IBaseSLInstance;
export declare type IConfiguration = Superlogin.IConfiguration;
export declare type IProfile = Superlogin.IProfile;
export declare type ISLInstance = Superlogin.ISLInstance;
export declare type ISecurityDoc = Superlogin.ISecurityDoc;
export declare type ISession = Superlogin.ISession;
export declare type IUserConfig = Superlogin.IUserConfig;
export declare type IUserDoc<Profile extends IProfile = IProfile> = Superlogin.IUserDoc<Profile>;
export declare type Strategy = PassportStrategy;
declare const init: <Profile extends Superlogin.IProfile = Superlogin.IProfile>(configData: Superlogin.IUserConfig, passport?: PassportStatic, userDB?: PouchDB.Database<Superlogin.IUserDoc<Profile>>, couchAuthDB?: PouchDB.Database<{}>) => Promise<Superlogin.ISLInstance>;
export default init;
